system:
  name: Boat2D
  signals:
    states:
      initial_value: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      lower_bound: [-10.0, -10.0, -3.141592653589793, -10.0, -10.0, -10.0]
      upper_bound: [10.0, 10.0, 3.141592653589793, 10.0, 10.0, 10.0]
      component:
        q: 3
        dq: 3

    inputs:
      initial_value: [0.0, 0.0]
      lower_bound: [-10000.0, -1000.0]
      upper_bound: [10000.0, 1000.0]

    outputs:
      initial_value: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      lower_bound: [-10.0, -10.0, -3.141592653589793, -10.0, -10.0, -10.0]
      upper_bound: [10.0, 10.0, 3.141592653589793, 10.0, 10.0, 10.0]
      component:
        q: 3
        dq: 3

mechanical:
  dof: 3 # x, y, theta
  mass: 1000.0
  inertia: 1000.0

geometry:
  thrust_offset: 3.0 # distance from center of mass to thrust point
  lateral_area: 6.0
  frontal_area: 1.5
  length_overall: 6.0

hydrodynamics:
  water_density: 1000.0
  linear_damping_coefficients: [2000.0, 20000.0, 10000.0]
  quadratic_damping_coefficients:
    cx_max: 0.5
    cy_max: 0.6
    cm_max: 0.1
